### ISSUE TITLE
Highlighting is broken in strings containing the = character

### ISSUE THREAD

**Issue by nikolai-in** [chouzz/vscode-innosetup#107]
## Description

I believe that the syntax is broken when a string contains quotes after the `=` character. When this happens, the editor thinks that the string ends after the first quote.

## Screenshots
![Line 39](https://user-images.githubusercontent.com/87097942/216396472-c50a56f7-8152-4992-83b7-d23ceef0eaa2.png)

```iss
[Run]
Filename: {sys}\sc.exe; Parameters: "create dotnetcorewinservice binPath= ""{app}\bin\Release\net451\win7-x64\WinServiceDemo.exe"" start= auto" ; Flags: runhidden
```

**Comment by chouzz** [comment]
Yeal, I will try to fix this problem
