### ISSUE TITLE
Support on hover feature

### ISSUE THREAD

**Issue by chouzz** [chouzz/vscode-innosetup#30]
Maybe we can support on hover feature, after hover in some words, we can show some helpful information from innosetup.

**Comment by pzhlkj6612** [comment]
Making [jrsoftware/issrc](https://github.com/jrsoftware/issrc) as a submodule, parsing the help text in it and generating the hover tip could be a way to it.

**Comment by chouzz** [comment]
This is what i am doing now.

**Comment by chouzz** [comment]
Closed as it's completed in v1.9.0
