### ISSUE TITLE
Remove broken commands

### ISSUE THREAD

**Issue by chouzz** [chouzz/vscode-innosetup#49]
The commands `Inno Setup: Save & Compile Script` and `Inno Setup: Create Build Task` are broken , we need remove or fix them.

**Screenshot**:

![image](https://user-images.githubusercontent.com/18023066/184903205-6b8ba382-26f0-4df7-8ee6-db4c45b58c45.png)

**Comment by Artanemus** [comment]
VSC the error reported
"Cannot destructure property 'alwaysShowOutput' of '(intermediate value)' as it is undefined."
Java script error - It would be nice if you can find the time to fix it - very useful plug-in for VSC
(Perhaps API returns null or the array for params has the wrong length)

**Comment by chouzz** [comment]
Sure, I will fix it and release new version soon.

**Comment by Artanemus** [comment]
Thanks for the fix - works great!
